{% set version = "2.3.8" %}

package:
  name: box2d-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/box2d-py/box2d-py-{{ version }}.tar.gz
  sha256: bdacfbbc56079bb317548efe49d3d5a86646885cc27f4a2ee97e4b2960921ab7

build:
  number: 9
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - swig                                   # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - swig
  run:
    - python

test:
  imports:
    - Box2D

about:
  home: https://github.com/openai/box2d-py
  license: Zlib
  license_file: LICENSE
  summary: 'A repackaged version of https://github.com/pybox2d/pybox2d'

  description: 'A repackaged version of https://github.com/pybox2d/pybox2d'
  dev_url: https://github.com/openai/box2d-py

extra:
  recipe-maintainers:
    - h-vetinari
